services:
  - type: worker
    name: price-tracker-bot
    env: node
    buildCommand: |
      apt-get update -y &&
      apt-get install -y wget gnupg &&
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&
      echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list &&
      apt-get update -y &&
      apt-get install -y google-chrome-stable &&
      npm install
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"